on:
  schedule:
    - cron: "0 9 * * *"  # Runs daily at 9 AM UTC (1 AM PST)
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fetch_posts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.2"
      - run: pip install -r requirements.txt
      - run: python YesterdayPostGrabberJSON.py
      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5